volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  lava-monitoring:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: lava-prometheus
    volumes:
       - type: volume
         source: prometheus_data
         target: /prometheus
       - type: bind
         source: ./prometheus
         target: /etc/prometheus
         read_only: true 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - 49090:9090
    networks:
      - lava-monitoring
    restart: always

  # default login credentials: admin/admin
  grafana:
    image: grafana/grafana:latest
    env_file: ./grafana/grafana.conf
    container_name: lava-grafana
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 49999:3000
    networks:
      - lava-monitoring
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    container_name: lava-alertmanager
    networks:
      - lava-monitoring
    ports:
      - 49093:9093
    volumes:
      - type: bind
        source: ./alertmanager
        target: /etc/alertmanager
        read_only: true
    command: [
      '--config.file=/etc/alertmanager/alertmanager.yml',
      '--log.level=debug',
    ]
    hostname: 'alertmanager'
    restart: always
